kind: Secret
type: Opaque
apiVersion: v1
metadata:
  name: docker-pull-secret
  annotations:
    avp.kubernetes.io/path: "nonprod-secret" # The name of your AWS Secret
data:
  username: <argocd-github-username | base64encode>
  password: <argocd-image-updater-github-token | base64encode>
